In [2]:
import torch

In [18]:
x=torch.rand(4,5)
x
x.shape  # get shape size()
x.numel()  # get total number

20

In [ ]:
x=x.reshape(5,-1)
x
# 我们不需要通过手动指定每个维度来改变形状。 也就是说，如果我们的目标形状是（高度,宽度） 
# 那么在知道宽度后，高度会被自动计算得出，不必我们自己做除法。 -1就可以实现这个功能


tensor([[0.4061, 0.9933, 0.0220, 0.1250],
        [0.9081, 0.3697, 0.1696, 0.7449],
        [0.7264, 0.1441, 0.6929, 0.7978],
        [0.0422, 0.5310, 0.8978, 0.7602],
        [0.6280, 0.4317, 0.9179, 0.9022]])

In [26]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [3]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [4]:
torch.rand(2,3,4)

tensor([[[0.9671, 0.4905, 0.8243, 0.1358],
         [0.5293, 0.3159, 0.9634, 0.5686],
         [0.9572, 0.4011, 0.2950, 0.5859]],

        [[0.2354, 0.7205, 0.5160, 0.3615],
         [0.2598, 0.3169, 0.4580, 0.4365],
         [0.2921, 0.0231, 0.1599, 0.7985]]])